<a href="https://colab.research.google.com/github/gymnopedies7/tensorflow_tutorial/blob/master/tensorflow_tutorial_iris__hidden_layer_batchnormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Library 불러오기
import tensorflow as tf
import pandas as pd

In [4]:
# Data 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()
아이리스[['품종']].nunique()

품종    3
dtype: int64

In [5]:
# Data dummy 처리(원핫인코딩)

one_hot = pd.get_dummies(아이리스)
one_hot.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [6]:
# 독립변수, 종속변수 구분
독립 = one_hot[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = one_hot[['품종_setosa', '품종_versicolor','품종_virginica']]

In [7]:
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 모델 구조만들기
'''
X = tf.keras.layers.Input(shape=[4])
H1 = tf.keras.layers.Dense(8, activation = 'swish')(X)
H2 = tf.keras.layers.Dense(8, activation = 'swish')(H1)
H3 = tf.keras.layers.Dense(8, activation = 'swish')(H2)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H3)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics = 'accuracy')
'''

In [8]:
# BatchNormalization 수행
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics = 'accuracy')

In [9]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
batch_normalization (BatchNo (None, 8)                 32        
_________________________________________________________________
activation (Activation)      (None, 8)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
batch_normalization_1 (Batch (None, 8)                 32        
_________________________________________________________________
activation_1 (Activation)    (None, 8)                

In [ ]:
model.fit(독립,종속, epochs=1000, verbose=1)


In [12]:
print(model.predict(독립[-20:]))
print(종속[-20:])

[[1.15803568e-05 2.59691407e-03 9.97391462e-01]
 [3.89472916e-07 1.01512633e-05 9.99989510e-01]
 [9.15840019e-07 4.75733286e-05 9.99951482e-01]
 [1.42290024e-03 1.38769180e-01 8.59807849e-01]
 [1.32953210e-06 5.10488776e-03 9.94893789e-01]
 [8.66620940e-06 7.59385657e-05 9.99915361e-01]
 [4.81482854e-10 7.22007477e-04 9.99278009e-01]
 [2.09925420e-05 7.57675292e-03 9.92402315e-01]
 [1.52491877e-04 1.20298453e-01 8.79549086e-01]
 [6.50003421e-05 4.54614783e-04 9.99480426e-01]
 [2.25128346e-07 9.28413613e-08 9.99999642e-01]
 [1.20642071e-07 1.58547300e-05 9.99984026e-01]
 [3.34939364e-06 1.05377836e-02 9.89458919e-01]
 [5.60177511e-07 6.31110925e-06 9.99993086e-01]
 [1.44191805e-08 2.70900617e-08 1.00000000e+00]
 [2.75519909e-07 1.29354333e-07 9.99999642e-01]
 [5.62850728e-05 3.96525487e-03 9.95978475e-01]
 [9.46873333e-05 1.52112124e-03 9.98384237e-01]
 [1.94456562e-09 1.29161067e-02 9.87083912e-01]
 [5.90327772e-06 1.65182844e-01 8.34811270e-01]]
     품종_setosa  품종_versicolor  품종_virgi

In [ ]:
print(model.get_weights())

Weight를 보면 

1열 0.156 , 2.065, -2.917, -1.574, (0.824)


이게 setosa 에 대한 가중치임. 그리고 마지막 0.824는 편향(bias)